### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by linshoa** [mangye16/Visible-Thermal-Person-Re-Identification#5]
Hi~
Your jobs are so great!
I have a question about your evaluation on SYSU-MM01 . From the paper of [wu](https://github.com/wuancong/SYSU-MM01), I see that:

> Notice that matching is conducted between cameras in different locations, that is, camera 2 and camera 3 are in the same location, so probe images of **camera 3 skip the gallery images of camera 2**. After computing similarities, we can get a ranking list according to descending order of similarities.

I was really confused~ Though camera 3 and camera 2 are the same location, but they are not the same modality, why should we skip it? Btw, do you evaluate with that skipping?

**Comment by mangye16** [comment]
Hi,

Actually, there are two different evaluation protocols (indoor search and all search), as mentioned in their main manuscript. You may need to double-check it again.

We have also included two different evaluation protocols in the evaluation code in [data_manager.py](https://github.com/mangye16/Cross-Modal-Re-ID-baseline/blob/master/data_manager.py). The option is shown in "--mode indoor or all" in [test.py](https://github.com/mangye16/Cross-Modal-Re-ID-baseline/blob/master/test.py).

**Comment by linshoa** [comment]
> Hi,
> 
> Actually, there are two different evaluation protocols (indoor search and all search), as mentioned in their main manuscript. You may need to double-check it again.
> 
> We have also included two different evaluation protocols in the evaluation code in [data_manager.py](https://github.com/mangye16/Cross-Modal-Re-ID-baseline/blob/master/data_manager.py). The option is shown in "--mode indoor or all" in [test.py](https://github.com/mangye16/Cross-Modal-Re-ID-baseline/blob/master/test.py).

Thanks very much for your reply~

From [wu's evaluation_SYSU_MM01.m](https://github.com/wuancong/SYSU-MM01/blob/master/evaluation/evaluation_SYSU_MM01.m), I see that:

> cam_id = [1 **2 **2**** 4 5 6]; % **camera 2 and 3 are in the same location**

So I think the author may take camera 2 and camera 3 into the same camera in both different evaluation protocols. But in fact, do we need to do so?

**Comment by mangye16** [comment]
The main reason might be: they are in the same location, but the person images are captured in different time (RGB camera 2 in the daytime and Infrared cameras 3 at night). RGB-IR reid needs to search out the corresponding RGB images by given a query IR image. This setting would be similar to the real settings in some scenarios, for example, the criminal tries to investigate the environment in the daytime (the person image is captured by RGB camera mode), and then conduct the crime at night in the same location (the person image can only be captured by IR camera mode).

**Comment by linshoa** [comment]
Thanks, I got it
